### ISSUE TITLE
docker compose & Question about $MASTER_PORT_3306_TCP_ADDR

### ISSUE THREAD

**Issue by jamiejackson** [bergerx/docker-mysql-replication#3]
Where does `$MASTER_PORT_3306_TCP_ADDR` come from, and how does it work?

```bash
# If there is a linked master use linked container information
if [ -n "$MASTER_PORT_3306_TCP_ADDR" ]; then
  export MASTER_HOST=$MASTER_PORT_3306_TCP_ADDR
  export MASTER_PORT=$MASTER_PORT_3306_TCP_PORT
fi
```

https://github.com/bergerx/docker-mysql-replication/blob/7b51e8ba7901c0a7855a81cb15e377eb076ab860/5.7/replication-entrypoint.sh#L13

**Comment by jamiejackson** [comment]
Those `MASTER_*` environment variables are a side effect of using legacy links: https://docs.docker.com/compose/link-env-deprecated/

That explains why I had trouble converting the `docker run` commands to `docker-compose`.

**Comment by jamiejackson** [comment]
This seems to work:

```yaml
# docker-compose.yml
version: '3'
services:

  mysql_master:
    image: bergerx/mysql-replication:5.7
    container_name: mysql_master
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mysql_slave:
    image: bergerx/mysql-replication:5.7
    container_name: mysql_slave
    depends_on:
      - "mysql_master"
    ports: 
     - "3307:3306"
    links:
      - mysql_master:master
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MASTER_HOST=master
      - MASTER_PORT=3306
```
